### ISSUE TITLE
Question: license ?

### ISSUE THREAD

**Issue by arisada** [larsendt/hashtable#1]
Hi,

Your code seems very useful. I'm looking for an hashtable lib (that I may enhance if I need to) that I could use in my BSDv2-licensed project.
What is the license of your code ?

Thanks,

Aris

**Comment by larsendt** [comment]
Hey Aris,

I never actually expected anyone to take a look at this, so I'm pleasantly surprised. I hadn't really considered a license, but I'll put it under BSDv2. I'll put the license up later tonight.

Fair warning, this was one of my first medium-sized C projects, so it may have bugs and I'm a little unsure about the code quality. I'd be more than happy to take pull requests though!

Thanks for your interest,
Dane

**Comment by larsendt** [comment]
Ok, I've added the license, and pushed a couple uncommitted changes. 
Also, the ht_keys function is mostly a stub at the moment. If I have time this week I'll fix that.

Cheers,
Dane

**Comment by arisada** [comment]
Hi,

Don't worry, I'll post pull requests if I find/fix bugs. It's simply simplier for me to use your code inside my tool than rewrite it from scratch. Thanks for licensing your code :)

**Comment by larsendt** [comment]
No problem. Glad to see it getting some use :)

**Comment by arisada** [comment]
Please also add your copyright information into the source files :)

**Comment by arisada** [comment]
Please also add your copyright information into the source files :)

**Comment by larsendt** [comment]
Oop. I forgot about that. I'll do that shortly. Thanks for the reminder!

**Comment by larsendt** [comment]
How to you want me to mention your contributions? I was thinking of putting a contributors file in there with the license file.
