### ISSUE TITLE
Set global_seed to rand()

### ISSUE THREAD

**Issue by larsendt** [larsendt/hashtable#3]
global_seed should be randomly set each time to make it actually effective

**Comment by arisada** [comment]
It's hard to do without being invasive, because the APIs to to that securely are very different in function of the OS. Doing so will bloat your code a lot when it's very light right now.

**Comment by larsendt** [comment]
Hmm. I guess I didn't think about that. What is the purpose of a seed if it isn't set randomly? I guess rand() isn't sufficient for cryptography, but would it be good enough to deter an attacker?

**Comment by larsendt** [comment]
Are there other good reasons for crypto-quality randomness?

**Comment by arisada** [comment]
I think I added a setter for this global variable. You may add in the document that this seed should be initialized with strong random at the program startup.
And rand() must be seeded as well, generally with time() which is trivial to guess. I don't think it adds any security...

**Comment by larsendt** [comment]
Yep. Looks like there's a setter. I guess if there are any concerns, it can be set with good randomness. Thanks for the input!
