### ISSUE TITLE
test does not run

### ISSUE THREAD

**Issue by matthiasbeyer** [larsendt/hashtable#7]
The test does not work:

```
./hashtable-test: error while loading shared libraries: libhashtable.so: cannot open shared object file: No such file or directory
```

but the `libhashtable.so` exists!

**Comment by larsendt** [comment]
I can't seem to reproduce this. What does `ldd` say about hashtable-test?

**Comment by matthiasbeyer** [comment]
On my master, when typing in `make`:

```
$ make
gcc -Wall -Wextra -g -DDEBUG -DTEST src/hashtable.c src/murmur.c -fPIC -rdynamic -shared -o libhashtable.so
gcc src/main.c -lrt -L. -lhashtable -Wall -Wextra -g -DDEBUG -DTEST -o hashtable-test
./hashtable-test
./hashtable-test: error while loading shared libraries: libhashtable.so: cannot open shared object file: No such file or directory
Makefile:16: recipe for target 'hashtable-test' failed
make: *** [hashtable-test] Error 127
```

hope this helps!

**Comment by arisada** [comment]
Hi, try again with
LD=. ./hashtable-test

**Comment by matthiasbeyer** [comment]
Please tell me the complete commandline call for it, I tried several things which did not work!

**Comment by larsendt** [comment]
Also try

`LD_LIBRARY_PATH=. ./hashtable-test`

What OS are you using?

**Comment by matthiasbeyer** [comment]
This one works. I'm on arch linux!

Now it runs, but results in a segfault after some tests:

```
$ LD_LIBRARY_PATH=. ./hashtable-test 
[SUCCESS] Checking for key "teststring 1"
Value size: 13
Got: {"teststring 1": "teststring 2"}
[SUCCESS] Value size was 13 (desired 13)
Replacing {"teststring 1": "teststring 2"} with {"teststring 1": "teststring 3"}
src/hashtable.c:327 - ht_keys: too many keys, expected 1, got 1
[SUCCESS] HashTable has 1 keys
[SUCCESS] Keys is not null
Value size: 13
Got: {"teststring 1": "teststring 3"}
[SUCCESS] Value size was 13 (desired 13)
Removing entry with key "teststring 1"
[SUCCESS] Checking for removal of key "teststring 1"
[SUCCESS] HashTable has 0 keys
Stress testsrc/hashtable.c:360 - ht_resize(old=64, new=128)
Speicherzugriffsfehler (Speicherabzug geschrieben
```

I will solve this on my own, thank you for your help!

**Comment by matthiasbeyer** [comment]
Uh, bad news: My patches introduced this segfault. I will fix this as soon as possible (don't have enough time today, but hopefully tomorrow)! You can revert my changes if you want! I'll fix them up (without breaking the already published history of course) and submit a pull request for it as soon as I can!

So if you now revert my commits from #8 , you will be able to merge the stuff in again with my next pull request on the topic, but then including the fixes!
